/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "cpuUsage.h"

/** Initializes the cpuUsage module */
void
init_cpuUsage(void)
{
    const oid cpuUsageUser_oid[]    = { 1,3,6,1,4,1,1111,1,1,1 };
    const oid cpuUsageNice_oid[]    = { 1,3,6,1,4,1,1111,1,1,2 };
    const oid cpuUsageSystem_oid[]  = { 1,3,6,1,4,1,1111,1,1,3 };
    const oid cpuUsageIddle_oid[]   = { 1,3,6,1,4,1,1111,1,1,4 };
    const oid cpuUsageIo_oid[]      = { 1,3,6,1,4,1,1111,1,1,5 };
    const oid cpuUsageIrq_oid[]     = { 1,3,6,1,4,1,1111,1,1,6 };
    const oid cpuUsageSoftIrq_oid[] = { 1,3,6,1,4,1,1111,1,1,7 };

  DEBUGMSGTL(("cpuUsage", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("cpuUsageUser", handle_cpuUsageUser,
                               cpuUsageUser_oid, OID_LENGTH(cpuUsageUser_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("cpuUsageNice", handle_cpuUsageNice,
                               cpuUsageNice_oid, OID_LENGTH(cpuUsageNice_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("cpuUsageSystem", handle_cpuUsageSystem,
                               cpuUsageSystem_oid, OID_LENGTH(cpuUsageSystem_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("cpuUsageIddle", handle_cpuUsageIddle,
                               cpuUsageIddle_oid, OID_LENGTH(cpuUsageIddle_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("cpuUsageIo", handle_cpuUsageIo,
                               cpuUsageIo_oid, OID_LENGTH(cpuUsageIo_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("cpuUsageIrq", handle_cpuUsageIrq,
                               cpuUsageIrq_oid, OID_LENGTH(cpuUsageIrq_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("cpuUsageSoftIrq", handle_cpuUsageSoftIrq,
                               cpuUsageSoftIrq_oid, OID_LENGTH(cpuUsageSoftIrq_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_cpuUsageUser(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    //Declarando el puntero para guardar la referencia
    //al fichero que se abrira.
    FILE *file;

    //Declarando las variables necesarias para almacenar
    //la informacion que se obtendra.
    char cpu[10];
    int num, i;

    switch(reqinfo->mode) {

        case MODE_GET:
            //Abriendo fichero con permisos de lectura
            //y almacenando la referencia en la variable.
            file = fopen("/proc/stat", "r");

            //Leyendo nombre de cpu.
            //NT: Este valor no se utiliza, pero es necesario leerlo.
            fscanf(file, "%s\t", cpu);

            //Leyendo hasta llegar al valor que queremos.
            //NT: Leera hasta que i sea igual numero especificado,
            // i = 1 | cpuUsageUser.
            for (i = 1; i <= 1; i++)
                fscanf(file, "%d\t", &num);

            //Cerrando el fichero..
            fclose(file);

            //Devolviendo datos de consulta.
            snmp_set_var_typed_value(requests->requestvb, ASN_TIMETICKS,
                                    //Direccion de memoria.
                                    (u_char*) &num, 
                                    //Tamaño de los datos.
                                    sizeof(num));
            break;

        default:
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_cpuUsageUser\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_cpuUsageNice(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    FILE *file;
    char cpu[10];
    int num, i;

    switch(reqinfo->mode) {

        case MODE_GET:
            file = fopen("/proc/stat", "r");

            fscanf(file, "%s\t", cpu);

            //Leyendo hasta llegar al valor que queremos.
            //NT: Leera hasta que i sea igual numero especificado,
            // i = 1 | cpuUsageUser.
            // i = 2 | cpuUsageNice.
            for (i = 1; i <= 2; i++)
                fscanf(file, "%d\t", &num);

            fclose(file);

            //Devolviendo datos de consulta.
            snmp_set_var_typed_value(requests->requestvb, ASN_TIMETICKS,
                                    //Direccion de memoria.
                                    (u_char*) &num, 
                                    //Tamaño de los datos.
                                    sizeof(num));
            break;

        default:
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_cpuUsageNice\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_cpuUsageSystem(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    FILE *file;
    char cpu[10];
    int num, i;

    switch(reqinfo->mode) {

        case MODE_GET:
            file = fopen("/proc/stat", "r");

            fscanf(file, "%s\t", cpu);

            //Leyendo hasta llegar al valor que queremos.
            //NT: Leera hasta que i sea igual numero especificado,
            // i = 1 | cpuUsageUser.
            // i = 2 | cpuUsageNice.
            // i = 3 | cpuUsageSystem.
            for (i = 1; i <= 3; i++)
                fscanf(file, "%d\t", &num);

            fclose(file);

            //Devolviendo datos de consulta.
            snmp_set_var_typed_value(requests->requestvb, ASN_TIMETICKS,
                                    //Direccion de memoria.
                                    (u_char*) &num, 
                                    //Tamaño de los datos.
                                    sizeof(num));
            break;

        default:
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_cpuUsageSystem\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_cpuUsageIddle(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    FILE *file;
    char cpu[10];
    int num, i;

    switch(reqinfo->mode) {

        case MODE_GET:
            file = fopen("/proc/stat", "r");

            fscanf(file, "%s\t", cpu);

            //Leyendo hasta llegar al valor que queremos.
            //NT: Leera hasta que i sea igual numero especificado,
            // i = 1 | cpuUsageUser.
            // i = 2 | cpuUsageNice.
            // i = 3 | cpuUsageSystem.
            // i = 4 | cpuUsageIddle.
            for (i = 1; i <= 4; i++)
                fscanf(file, "%d\t", &num);

            fclose(file);

            //Devolviendo datos de consulta.
            snmp_set_var_typed_value(requests->requestvb, ASN_TIMETICKS,
                                    //Direccion de memoria.
                                    (u_char*) &num, 
                                    //Tamaño de los datos.
                                    sizeof(num));
            break;
        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_cpuUsageIddle\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_cpuUsageIo(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    FILE *file;
    char cpu[10];
    int num, i;

    switch(reqinfo->mode) {

        case MODE_GET:
            file = fopen("/proc/stat", "r");

            fscanf(file, "%s\t", cpu);

            //Leyendo hasta llegar al valor que queremos.
            //NT: Leera hasta que i sea igual numero especificado,
            // i = 1 | cpuUsageUser.
            // i = 2 | cpuUsageNice.
            // i = 3 | cpuUsageSystem.
            // i = 4 | cpuUsageIddle.
            // i = 5 | cpuUsageIo.
            for (i = 1; i <= 5; i++)
                fscanf(file, "%d\t", &num);

            fclose(file);

            //Devolviendo datos de consulta.
            snmp_set_var_typed_value(requests->requestvb, ASN_TIMETICKS,
                                    //Direccion de memoria.
                                    (u_char*) &num, 
                                    //Tamaño de los datos.
                                    sizeof(num));
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_cpuUsageIo\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_cpuUsageIrq(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    FILE *file;
    char cpu[10];
    int num, i;

    switch(reqinfo->mode) {

        case MODE_GET:
            file = fopen("/proc/stat", "r");

            fscanf(file, "%s\t", cpu);

            //Leyendo hasta llegar al valor que queremos.
            //NT: Leera hasta que i sea igual numero especificado,
            // i = 1 | cpuUsageUser.
            // i = 2 | cpuUsageNice.
            // i = 3 | cpuUsageSystem.
            // i = 4 | cpuUsageIddle.
            // i = 5 | cpuUsageIo.
            // i = 6 | cpuUsageIrq.
            for (i = 1; i <= 6; i++)
                fscanf(file, "%d\t", &num);

            fclose(file);

            //Devolviendo datos de consulta.
            snmp_set_var_typed_value(requests->requestvb, ASN_TIMETICKS,
                                    //Direccion de memoria.
                                    (u_char*) &num, 
                                    //Tamaño de los datos.
                                    sizeof(num));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_cpuUsageIrq\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_cpuUsageSoftIrq(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    FILE *file;
    char cpu[10];
    int num, i;

    switch(reqinfo->mode) {

        case MODE_GET:
            file = fopen("/proc/stat", "r");

            fscanf(file, "%s\t", cpu);

            //Leyendo hasta llegar al valor que queremos.
            //NT: Leera hasta que i sea igual numero especificado,
            // i = 1 | cpuUsageUser.
            // i = 2 | cpuUsageNice.
            // i = 3 | cpuUsageSystem.
            // i = 4 | cpuUsageIddle.
            // i = 5 | cpuUsageIo.
            // i = 6 | cpuUsageIrq.
            // i = 7 | cpuUsageSoftIrq.
            for (i = 1; i <= 7; i++)
                fscanf(file, "%d\t", &num);

            fclose(file);

            //Devolviendo datos de consulta.
            snmp_set_var_typed_value(requests->requestvb, ASN_TIMETICKS,
                                    //Direccion de memoria.
                                    (u_char*) &num, 
                                    //Tamaño de los datos.
                                    sizeof(num));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_cpuUsageSoftIrq\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
