/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "memoryUsage.h"
#include <sys/sysinfo.h>

/** Initializes the memoryUsage module */
void
init_memoryUsage(void)
{
    const oid memoryUsageTotalRam_oid[]  = { 1,3,6,1,4,1,1111,1,2,1 };
    const oid memoryUsageFreeRam_oid[]   = { 1,3,6,1,4,1,1111,1,2,2 };
    const oid memoryUsageSharedRam_oid[] = { 1,3,6,1,4,1,1111,1,2,3 };
    const oid memoryUsageBufferRam_oid[] = { 1,3,6,1,4,1,1111,1,2,4 };
    const oid memoryUsageTotalSwap_oid[] = { 1,3,6,1,4,1,1111,1,2,5 };
    const oid memoryUsageFreeSwap_oid[]  = { 1,3,6,1,4,1,1111,1,2,6 };

  DEBUGMSGTL(("memoryUsage", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("memoryUsageTotalRam", handle_memoryUsageTotalRam,
                               memoryUsageTotalRam_oid, OID_LENGTH(memoryUsageTotalRam_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("memoryUsageFreeRam", handle_memoryUsageFreeRam,
                               memoryUsageFreeRam_oid, OID_LENGTH(memoryUsageFreeRam_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("memoryUsageSharedRam", handle_memoryUsageSharedRam,
                               memoryUsageSharedRam_oid, OID_LENGTH(memoryUsageSharedRam_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("memoryUsageBufferRam", handle_memoryUsageBufferRam,
                               memoryUsageBufferRam_oid, OID_LENGTH(memoryUsageBufferRam_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("memoryUsageTotalSwap", handle_memoryUsageTotalSwap,
                               memoryUsageTotalSwap_oid, OID_LENGTH(memoryUsageTotalSwap_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("memoryUsageFreeSwap", handle_memoryUsageFreeSwap,
                               memoryUsageFreeSwap_oid, OID_LENGTH(memoryUsageFreeSwap_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_memoryUsageTotalRam(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{  
    //Declarando la estructura necesaria para almacenar
    //la informacion del sistema.
    struct sysinfo info;
    long result;

    switch(reqinfo->mode) {

        case MODE_GET:
            //Obteniendo informacion del sistema y guardandola
            //en la variable especificada.
            sysinfo(&info);
            result = info.totalram / 1.049e+6;

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                    //Direccion de memoria.
                                    (u_char*) &result, 
                                    //Tamaño de los datos.
                                    sizeof(info.totalram));
            break;

        default:
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_memoryUsageTotalRam\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_memoryUsageFreeRam(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    struct sysinfo info;
    long result;

    switch(reqinfo->mode) {

        case MODE_GET:
            sysinfo(&info);
            result = info.freeram / 1.049e+6;

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                    (u_char*) &result,
                                    sizeof(info.freeram));
            break;

        default:
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_memoryUsageFreeRam\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_memoryUsageSharedRam(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    struct sysinfo info;
    long result;

    switch(reqinfo->mode) {

        case MODE_GET:
            sysinfo(&info);
            result = info.sharedram / 1.049e+6; //convirtiendo de Byte a MibiByte

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                    (u_char*) &result,
                                    sizeof(info.sharedram));
            break;

        default:
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_memoryUsageSharedRam\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_memoryUsageBufferRam(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    struct sysinfo info;
    long result;

    switch(reqinfo->mode) {

        case MODE_GET:
            sysinfo(&info);
            result = info.bufferram / 1.049e+6;

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                    (u_char*) &result,
                                    sizeof(info.bufferram));
            break;

        default:
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_memoryUsageBufferRam\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_memoryUsageTotalSwap(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    struct sysinfo info;
    long result;

    switch(reqinfo->mode) {

        case MODE_GET:
            sysinfo(&info);
            result = info.totalswap / 1.049e+6;

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                    (u_char*) &result,
                                    sizeof(info.totalswap));
            break;

        default:
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_memoryUsageTotalSwap\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_memoryUsageFreeSwap(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    struct sysinfo info;
    long result;

    switch(reqinfo->mode) {

        case MODE_GET:
            sysinfo(&info);
            result = info.freeswap / 1.049e+6;

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                    (u_char*) &result,
                                    sizeof(info.freeswap));
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_memoryUsageFreeSwap\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
